import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {builders} from './models.js';
import {attachMarkers} from './markers.js';
const $=id=>document.getElementById(id),objects=[{"name":"Rosetta Stone","view":[3,2.1,8.8],"description":"A fragmented granodiorite stela from 196 BC, inscribed with the same priestly decree in three scripts: Egyptian hieroglyphs, Demotic, and ancient Greek. Discovered by French soldiers near Rashid (Rosetta) in 1799 during Napoleon’s Egyptian campaign, it became the linguistic key that unlocked hieroglyphic writing after more than a millennium of silence. Now the most visited object in the British Museum."},{"name":"Raptor 3","view":[4,1.5,9.8],"description":"SpaceX’s full-flow staged-combustion methalox rocket engine family, the first of its cycle type to fly. Raptor 3 eliminates external heat shields, integrates plumbing into the structure, and delivers ~250 tf sea-level thrust at ~1525 kg dry mass with chamber pressures around 330 bar. Designed for rapid reuse on Starship and Super Heavy."},{"name":"Venus de Milo","view":[2.1,1.05,9.6],"description":"Hellenistic marble statue of Aphrodite (c. 160–110 BC), discovered on the island of Melos in 1820 by a local farmer. Immediately claimed by French naval officers and presented to Louis XVIII, it has stood in the Louvre ever since. Famous for its serene contrapposto, missing arms, and the way it shaped Western ideals of classical female beauty despite belonging to a later period than initially claimed."},{"name":"Wright Flyer","view":[6,4.8,8.5],"description":"The world’s first successful powered, controlled, heavier-than-air flying machine. Designed and built by Wilbur and Orville Wright after four years of systematic research (gliders, wind-tunnel data, custom engine and propellers). On 17 December 1903 at Kill Devil Hills, North Carolina, it made four flights; the longest covered 852 feet in 59 seconds. Now permanently displayed at the Smithsonian National Air and Space Museum."},{"name":"Gutenberg Bible","view":[3,5,6.5],"description":"The first major European book printed with movable metal type, completed in Mainz around 1454–1455 by Johannes Gutenberg. Approximately 180 copies were produced (about 45 on vellum); roughly 49 survive in substantial form. Its 42-line pages, Gothic type, and unprecedented uniformity mark the beginning of the print revolution that transformed knowledge distribution."},{"name":"The Ninth Wave","view":[0.2,0.3,10.8],"description":"Ivan Aivazovsky’s 1850 masterpiece (oil on canvas, 221 × 332 cm), housed in the State Russian Museum, St. Petersburg. It shows shipwreck survivors clinging to a cross-shaped spar as the legendary “ninth wave”—the largest in a sequence—rises at dawn. The painting balances terror and hope through luminous color and a Christian metaphor of salvation."}];
const featureNotes=[
{'Top band of hieroglyphs':'These cartouches enclose the name of Ptolemy V. Thomas Young first proved they were phonetic spellings of a royal name in 1814—the breakthrough that made full decipherment possible.','Middle Demotic section':'The everyday cursive script of late Egyptian. Champollion matched its signs against the Greek text below to establish sound values across all three writing systems by 1822.','Broken edge':'The stone is only a surviving fragment of a larger temple stela. Current dimensions: 114 cm high × 72 cm wide; weight ≈ 760 kg.'},
{'Nozzle':'Filmless radiative cooling—the outer wall is designed to glow cherry-red in flight. No external heat shield is required.','Turbopumps':'Full-flow staged combustion: separate fuel-rich and oxygen-rich turbines feed a single combustion chamber. Highest chamber pressure of any operational rocket engine (~330 bar).','Propellant lines':'Sub-cooled liquid methane and liquid oxygen (methalox) at a mixture ratio of ~3.6:1. Lines are fully integrated into the engine structure for mass reduction and rapid reuse.'},
{'Missing arm':'Fragments recovered nearby suggest the left arm may have rested on a pillar or held an apple (alluding to the Judgment of Paris). The exact original pose remains unresolved.','Base (with inscription)':'A now-lost plinth fragment once bore the signature ‘Alexandros, son of Menides, of Antioch on the Maeander.’ The Louvre initially suppressed this Hellenistic attribution to present the statue as Classical.','Drapery':'The slipping himation is carved to paper-thin transparency over the hips while remaining solid marble—an extraordinary technical achievement of Hellenistic sculpture.'},
{'Wing warping cables':'Active lateral control by twisting the wingtips via cables linked to a hip cradle. This system was the Wrights’ decisive advantage over all previous experimenters.','Long skids':'No wheels—the aircraft launched from a 60-foot wooden rail and landed on these skids. Empty weight 605 lb; designed for soft sand.','Canard elevators':'Forward biplane surface providing pitch control. The Wrights called it the ‘front rudder’—the opposite configuration from modern aircraft.'},
{'Page':'42 lines per column in a double-column layout. Six compositors worked simultaneously on later sheets; each page required roughly a full day to set and proof.','Cover':'Most surviving copies were bound after printing. Original covers were typically wooden boards covered in leather or pigskin, often with metal clasps; few remain in their first bindings.','Words / text':'Latin Vulgate text set in a specially designed Gothic type. Spaces were left blank for hand-illuminated initials and rubrication, making every finished copy unique.'},
{'Cross-shaped raft':'Two spars lashed into a crude cross. A deliberate Christian symbol of salvation amid catastrophe; the survivors cling to it as their only hope.','Rising sun':'Warm golden light cutting across cold green water. Aivazovsky uses the dawn to soften the threat and suggest the possibility of survival.','Wave crest':'The ‘ninth wave’ of maritime folklore—the climactic, most destructive wave after a series of building seas—poised to break over the raft.'}
];
const cache=[],annotations=[],clock=new T.Clock(),pointers=new Set();let renderer,scene,camera,controls,model,exhibitKey,venusFill,current=0,interaction=null,interactionStart=0,cameraTween=null,start=null,selectToken=0,ready=false,thumbBusy=false,thumbAgain=false;
objects.forEach((o,i)=>{let b=document.createElement('button');b.className='gallery-card';b.id=`tab-${i}`;b.type='button';b.setAttribute('aria-label',o.name);b.setAttribute('aria-pressed',i===0?'true':'false');let c=document.createElement('canvas');c.width=352;c.height=210;c.setAttribute('aria-hidden','true');let title=document.createElement('span');title.className='gallery-card-title';title.textContent=o.name;let fact=document.createElement('span');fact.className='gallery-card-fact fact-check';fact.innerHTML='<img src="grok-mark.svg" alt=""><span>Fact-checked by Grok</span>';b.append(c,title,fact);b.onclick=()=>select(i);b.onkeydown=e=>{let n=e.key==='ArrowRight'?i+1:e.key==='ArrowLeft'?i-1:e.key==='Home'?0:e.key==='End'?objects.length-1:null;if(n!==null){e.preventDefault();n=(n+objects.length)%objects.length;$(`tab-${n}`).focus()}};$('gallery-grid').append(b)});
$('gallery-trigger').onclick=()=>{$('gallery-dialog').showModal()};$('gallery-close').onclick=()=>$('gallery-dialog').close();$('gallery-dialog').addEventListener('click',e=>{if(e.target===$('gallery-dialog'))$('gallery-dialog').close()});
function lights(s,shadows=true,power=520){let spot=new T.SpotLight('#ffe5b0',power,38,.50,.18,2);spot.position.set(-2.2,8.5,3.2);spot.target.position.set(0,-1,0);spot.castShadow=shadows;spot.shadow.mapSize.set(2048,2048);spot.shadow.camera.near=.2;spot.shadow.camera.far=30;spot.shadow.bias=-.00018;spot.shadow.normalBias=.012;spot.shadow.radius=.55;s.add(spot,spot.target);return spot}
function configureExhibitLighting(i){
 const venus=i===2;venusFill.visible=venus;
 exhibitKey.position.set(...(venus?[-2.2,4,6.5]:[-2.2,8.5,3.2]));
 exhibitKey.target.position.set(0,venus?.2:-1,0);
 exhibitKey.intensity=venus?430:650;exhibitKey.angle=venus?.64:.50;
 exhibitKey.penumbra=venus?.42:.18;exhibitKey.shadow.radius=venus?3:.55;
}
async function getModel(i){if(!cache[i]){cache[i]=builders[i]();if(cache[i].userData.ready)await cache[i].userData.ready}else if(cache[i].userData.ready)await cache[i].userData.ready;if(!annotations[i])annotations[i]=attachMarkers(i,cache[i]);return cache[i]}
async function init(){try{scene=new T.Scene();scene.background=new T.Color('#000000');camera=new T.PerspectiveCamera(35,1,.05,120);renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('viewport').append(renderer.domElement);exhibitKey=lights(scene,true,650);venusFill=new T.DirectionalLight('#fff7e9',1.65);venusFill.position.set(1,1.8,6);venusFill.visible=false;scene.add(venusFill);const backlight=new T.DirectionalLight('#fff0dc',2.3);backlight.position.set(2.5,3.8,-5.5);backlight.target.position.set(0,.1,0);scene.add(backlight,backlight.target);camera.position.set(...objects[0].view);

controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=34;controls.maxPolarAngle=Math.PI-.06;controls.minPolarAngle=.06;controls.autoRotateSpeed=.65;
renderer.domElement.onpointerdown=e=>{pointers.add(e.pointerId);start=pointers.size===1?{x:e.clientX,y:e.clientY,time:performance.now()}:null};renderer.domElement.onpointerup=e=>{pointers.delete(e.pointerId);if(!start)return;let clicked=Math.hypot(e.clientX-start.x,e.clientY-start.y)<6&&performance.now()-start.time<450;start=null;if(!clicked||!model)return;let r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);let hits=ray.intersectObject(model,true).filter(h=>{for(let node=h.object;node;node=node.parent)if(!node.visible||node.name==='flight-effects'||node.name==='reconstruction-hologram')return false;return true}),markerHit=hits.find(h=>h.object.name==='feature-marker');if(markerHit){let blocker=hits.find(h=>h.object!==markerHit.object&&h.object.isMesh&&h.object.material!==model.userData.flameMat);if(!blocker||markerHit.distance<=blocker.distance+.08){let label=markerHit.object.userData.label;toggleReconstruction(label);showFeature(label);return}}if(![1,3,4].includes(current))return;if(hits.some(h=>h.object.isMesh&&h.object.material!==model.userData.flameMat))action()};renderer.domElement.onpointercancel=e=>{pointers.delete(e.pointerId);start=null};
$('viewport').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Enter',' '].includes(e.key))return;e.preventDefault();if(e.key==='Enter'||e.key===' ')return action();let offset=camera.position.clone().sub(controls.target);if(e.key==='+'||e.key==='-')offset.multiplyScalar(e.key==='+'?.9:1.1);else{let s=new T.Spherical().setFromVector3(offset);s.theta+=e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0;s.phi=T.MathUtils.clamp(s.phi+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0),.06,Math.PI-.06);offset.setFromSpherical(s)}camera.position.copy(offset.add(controls.target))};new ResizeObserver(resize).observe($('viewport'));ready=true;resize();await select(0);animate();thumbnails().catch(console.error)}catch(e){console.error(e);$('loading').hidden=false;$('loading').classList.add('error');$('loading').setAttribute('aria-label','Unable to display 3D. Enable WebGL and reload.')}}
function resize(){if(!renderer)return;let r=$('viewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
async function select(i){let token=++selectToken;stopBurn();hideFeature();if(model?.userData.reconstructions)Object.values(model.userData.reconstructions).forEach(o=>{o.visible=false;o.userData.reveal=0;o.userData.targetReveal=0});current=i;const fromGallery=$('gallery-dialog').open;if(fromGallery){$('gallery-dialog').close();$('gallery-trigger').focus()}document.querySelectorAll('.gallery-card').forEach((t,n)=>t.setAttribute('aria-pressed',n===i?'true':'false'));$('detail-title').textContent=objects[i].name;$('detail-description').textContent=objects[i].description;$('action').hidden=![1,3,4].includes(i);$('credits').hidden=i!==2;$('action').disabled=false;if(i===1)$('action').setAttribute('aria-label','Ignite engine');else $('action').setAttribute('aria-label',i===3?'Start wind and propellers':'Open or close Bible');if(!ready)return;$('loading').hidden=false;let next=await getModel(i);if(token!==selectToken)return;if(model)scene.remove(model);model=next;scene.add(model);configureExhibitLighting(i);$('viewport').setAttribute('aria-label',objects[i].name+'. Drag to orbit; scroll to zoom. Marked details: '+annotations[i].rings.map(r=>r.userData.label).join(', '));reset();if(i===1){$('action-icon').innerHTML='<path d="M12 3c-2 4-6 7-6 12a6 6 0 1 0 12 0c0-5-4-8-6-12z"/><path d="M9 16c0 2 1.2 3 3 3"/>'}else if(i===3){$('action-icon').innerHTML='<path d="M3 7h12a3 3 0 1 0-3-3M3 12h17M3 17h10a3 3 0 1 1-3 3"/>'}else if(i===4){$('action-icon').innerHTML='<path d="M12 5H3v14h9V5zm0 0h9v14h-9"/><path d="M12 5v14"/>'}$('loading').hidden=true}
function toggleReconstruction(label){
 const parts=model?.userData.reconstructions;if(!parts)return;
 for(const [name,object] of Object.entries(parts)){
  const show=name===label&&!object.userData.targetReveal;
  object.userData.targetReveal=show?1:0;if(show)object.visible=true;
  if(current===0&&name===label&&show){
   const target=controls.target.clone();target.y=.72;
   const to=camera.position.clone().sub(controls.target);to.setLength(Math.max(to.length(),12.6));to.add(target);
   cameraTween={start:performance.now(),duration:800,from:camera.position.clone(),to,targetFrom:controls.target.clone(),targetTo:target};
  }
 }
}
function showFeature(label){let text=featureNotes[current]?.[label];if(!text)return;$('feature-title').textContent=label;$('feature-description').textContent=text;$('repair-caption').hidden=!model?.userData.reconstructions?.[label]?.userData.targetReveal;$('feature-panel').hidden=false;$('feature-close').focus()}function hideFeature(){$('feature-panel').hidden=true}
function reset(){if(!ready)return;let targetPosition=new T.Vector3(...objects[current].view);let width=current===3?6.4:current===4?5.2:current===5?5.8:3.1;let fit=width/(2*Math.tan(camera.fov*Math.PI/360)*camera.aspect)*1.14;targetPosition.setLength(Math.max(targetPosition.length(),Math.min(fit,32)));let view=new T.Vector3(...objects[current].view),right=new T.Vector3(view.z,0,-view.x).normalize();let targetFocus=right.multiplyScalar(-.9);targetFocus.y=-.15;cameraTween={start:performance.now(),duration:620,from:camera.position.clone(),to:targetPosition,targetFrom:controls.target.clone(),targetTo:targetFocus};}
function easeOut(t){return 1-Math.pow(1-T.MathUtils.clamp(t,0,1),3)}
function stopBurn(){if(cache[3])cache[3].userData.effects.visible=false;interaction=null;$('ignition').hidden=true;$('action').disabled=false;if(cache[1]){cache[1].userData.flame.visible=false;cache[1].userData.light.intensity=0;cache[1].userData.flameMat.uniforms.envelope.value=0}}
function action(){if(!model)return;if(current===1&&interaction!=='ignite'){interaction='ignite';interactionStart=performance.now();$('ignition').setAttribute('aria-label','Ignition progress');model.userData.flameMat.uniforms.envelope.value=0;model.userData.flame.visible=true;$('ignition').hidden=false;$('action').disabled=true;$('timer-progress').style.strokeDashoffset=157.08}else if(current===3&&interaction!=='flight'){interaction='flight';interactionStart=performance.now();model.userData.effects.visible=true;model.userData.windRibbons.forEach(o=>o.material.opacity=0);model.userData.windParticles.forEach(o=>o.mesh.material.opacity=0);$('ignition').setAttribute('aria-label','Flight effect progress');$('ignition').setAttribute('aria-valuenow','0');$('ignition').hidden=false;$('action').disabled=true;$('timer-progress').style.strokeDashoffset=157.08}else if(current===4){model.userData.targetOpen=1-model.userData.targetOpen;$('action').setAttribute('aria-label',model.userData.targetOpen?'Close Bible':'Open Bible')}}
function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.1),now=performance.now();if(interaction){let p=Math.min((now-interactionStart)/3000,1),v=easeOut(p);$('timer-progress').style.strokeDashoffset=157.08*(1-v);$('ignition').setAttribute('aria-valuenow',Math.round(v*100));if(interaction==='ignite'){let data=cache[1].userData;data.flameMat.uniforms.time.value=now/1000;let arrival=easeOut((now-interactionStart)/350),fade=p>.94?1-easeOut((p-.94)/.06):1;data.flameMat.uniforms.envelope.value=arrival*fade;data.light.intensity=(45+Math.sin(now*.057)*6)*arrival*fade}else if(interaction==='flight'){const plane=cache[3],d=plane.userData,envelope=easeOut(p/.14)*(1-easeOut((p-.72)/.28));for(let ribbon of d.windRibbons)ribbon.material.opacity=.22*envelope;for(let q of d.windParticles){q.phase=(q.phase+dt*q.rate*envelope)%1;q.mesh.position.copy(q.curve.getPointAt(q.phase));q.mesh.material.opacity=.85*envelope}for(let side of ['left','right'])plane.getObjectByName('flyer-propeller-'+side).rotation.z+=dt*24*envelope}if(p>=1)stopBurn()}if(cache[4]){let d=cache[4].userData;d.open=T.MathUtils.lerp(d.open,d.targetOpen,matchMedia('(prefers-reduced-motion: reduce)').matches?1:Math.min(dt*3.5,1));if(Math.abs(d.open-d.targetOpen)<.0001)d.open=d.targetOpen;d.update(d.open)}if(cameraTween){let t=Math.min((now-cameraTween.start)/cameraTween.duration,1),v=easeOut(t);camera.position.lerpVectors(cameraTween.from,cameraTween.to,v);controls.target.lerpVectors(cameraTween.targetFrom,cameraTween.targetTo,v);if(t>=1)cameraTween=null}controls.update(dt);const marks=annotations[current];marks?.update();if(marks)for(const ring of marks.rings){const pulse=1+.035*Math.sin(now*.003);ring.scale.set(.024*pulse,.024*pulse,1)}if(model?.userData.reconstructions)for(const reconstruction of Object.values(model.userData.reconstructions))if(reconstruction.visible){const d=reconstruction.userData;d.reveal=T.MathUtils.lerp(d.reveal,d.targetReveal,1-Math.exp(-dt*5));const pulse=matchMedia('(prefers-reduced-motion: reduce)').matches?1:.95+.05*Math.sin(now*.0018);for(const item of d.pulseMaterials||[])item.material.opacity=item.opacity*pulse*d.reveal;if(!d.targetReveal&&d.reveal<.005)reconstruction.visible=false}renderer.render(scene,camera)}
async function thumbnails(){if(thumbBusy){thumbAgain=true;return}thumbBusy=true;await Promise.all(objects.map((_,i)=>getModel(i)));const tr=new T.WebGLRenderer({antialias:true,alpha:true});tr.setSize(352,210);tr.setPixelRatio(1);tr.outputColorSpace=T.SRGBColorSpace;tr.toneMapping=T.ACESFilmicToneMapping;tr.toneMappingExposure=1.45;tr.setClearColor(0x000000,0);tr.shadowMap.enabled=true;tr.shadowMap.type=T.PCFSoftShadowMap;let ts=new T.Scene();ts.background=null;lights(ts,true);let cam=new T.PerspectiveCamera(34,352/210,.01,100);for(let i=0;i<objects.length;i++){let original=await getModel(i);const duplicate=original.clone(true);const remove=[];duplicate.traverse(o=>{if(o.name==='feature-marker'||o.name==='flight-effects'||o.name==='reconstruction-hologram')remove.push(o)});remove.forEach(o=>o.removeFromParent());if(i===1){duplicate.remove(duplicate.children.find(o=>o.type==='Group'));duplicate.traverse(o=>{if(o.isPointLight)o.intensity=0})}if(i===4)duplicate.userData.update=undefined;let bound=new T.Box3().setFromObject(duplicate),size=bound.getSize(new T.Vector3()),center=bound.getCenter(new T.Vector3());duplicate.position.sub(center);ts.add(duplicate);let radius=Math.max(size.y,size.x/cam.aspect,size.z*.7),distance=radius/(2*Math.tan(cam.fov*Math.PI/360))*1.36;let direction=new T.Vector3(...objects[i].view).normalize();cam.position.copy(direction.multiplyScalar(distance));cam.lookAt(0,0,0);tr.render(ts,cam);$(`tab-${i}`).querySelector('canvas').getContext('2d').drawImage(tr.domElement,0,0);ts.remove(duplicate)}tr.dispose();thumbBusy=false;if(thumbAgain){thumbAgain=false;thumbnails().catch(console.error)}}
$('feature-close').onclick=hideFeature;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('feature-panel').hidden)hideFeature()});$('credits').onclick=()=>$('credits-dialog').showModal();$('credits-close').onclick=()=>$('credits-dialog').close();$('action').onclick=action;$('rotate').onclick=()=>{if(!controls)return;controls.autoRotate=!controls.autoRotate;$('rotate').setAttribute('aria-pressed',controls.autoRotate)};$('reset').onclick=reset;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};T.DefaultLoadingManager.onLoad=()=>{if(ready)thumbnails().catch(console.error)};init();
